Repository ismahl95/Nuke-PowerPlant-Monitoring-System, pull requests merged in 2024-10, with the labels that each got.

#5 Security Impl
  .github/workflows/ci.yml
  backend/pom.xml
  backend/src/main/java/com/ihl95/nuclear/nuclearPlant/application/controller/NuclearPlantController.java
  backend/src/main/java/com/ihl95/nuclear/security/AuthenticationRequest.java
  backend/src/main/java/com/ihl95/nuclear/security/JwtRequestFilter.java
  backend/src/main/java/com/ihl95/nuclear/security/JwtUtil.java
  backend/src/main/java/com/ihl95/nuclear/security/config/SecurityConfigurer.java
  backend/src/main/java/com/ihl95/nuclear/security/controller/AuthController.java
  backend/src/main/java/com/ihl95/nuclear/swagger/OpenApiConfig.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/ihl95/nuclear/nuclearPlant/controller/NuclearPlantIntegrationTest.java
  backend/src/test/java/com/ihl95/nuclear/nuclearPlant/service/NuclearPlantUnitTest.java
Labels: enhancement

#3 Nuclear plant service has its own interface & get all supliers implemented
  .github/workflows/ci.yml
  backend/pom.xml
  backend/src/main/java/com/ihl95/nuclear/nuclearPlant/application/controller/NuclearPlantController.java
  backend/src/main/java/com/ihl95/nuclear/nuclearPlant/application/service/NuclearPlantService.java
  backend/src/main/java/com/ihl95/nuclear/nuclearPlant/application/service/NuclearPlantServiceImpl.java
  backend/src/main/java/com/ihl95/nuclear/security/AuthenticationRequest.java
  backend/src/main/java/com/ihl95/nuclear/security/JwtRequestFilter.java
  backend/src/main/java/com/ihl95/nuclear/security/JwtUtil.java
  backend/src/main/java/com/ihl95/nuclear/security/config/SecurityConfigurer.java
  backend/src/main/java/com/ihl95/nuclear/security/controller/AuthController.java
  backend/src/main/java/com/ihl95/nuclear/supplier/application/controller/SupplierController.java
  backend/src/main/java/com/ihl95/nuclear/supplier/application/mapper/SupplierMapper.java
  backend/src/main/java/com/ihl95/nuclear/supplier/application/service/SupplierService.java
  backend/src/main/java/com/ihl95/nuclear/supplier/application/service/SupplierServiceImpl.java
  backend/src/main/java/com/ihl95/nuclear/supplier/infraestructure/SupplierRepository.java
  backend/src/main/java/com/ihl95/nuclear/swagger/OpenApiConfig.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/ihl95/nuclear/nuclearPlant/controller/NuclearPlantIntegrationTest.java
  backend/src/test/java/com/ihl95/nuclear/nuclearPlant/service/NuclearPlantUnitTest.java
Labels: enhancement

#7 docs: Database diagram
  docs/database-diagram.md
Labels: documentation

#8 docs: README updated
  README.md
Labels: documentation

#9 feat(OpenApi): division by definitions & nuclear plant controller documented
  .github/workflows/ci.yml
  README.md
  backend/src/main/java/com/ihl95/nuclear/nuclearPlant/application/controller/NuclearPlantController.java
  backend/src/main/java/com/ihl95/nuclear/security/controller/AuthController.java
  backend/src/main/java/com/ihl95/nuclear/swagger/OpenApiConfig.java
Labels: documentation

#10 docs: documentation updated
  README.md
Labels: documentation

#11 feat(docker-compose): SonarQube local integration
  docker/docker-compose.yml
Labels: enhancement

#14 fix(Sonar): Uncovered tests
  backend/pom.xml
  backend/src/test/java/com/ihl95/nuclear/security/CustomUserDetailsServiceTest.java
Labels: enhancement

#16 feat(Actions): new pipelines
  .github/workflows/ci.yml
Labels: enhancement

#17 test(User): User entity tests
  backend/src/test/java/com/ihl95/nuclear/user/UserTest.java
Labels: bug

#20 feat(Supplier): Supplier can be found by id
  .github/workflows/ci.yml
  backend/src/main/java/com/ihl95/nuclear/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/ihl95/nuclear/supplier/application/controller/SupplierController.java
  backend/src/main/java/com/ihl95/nuclear/supplier/application/exception/SupplierException.java
  backend/src/main/java/com/ihl95/nuclear/supplier/application/service/SupplierService.java
  backend/src/main/java/com/ihl95/nuclear/supplier/application/service/SupplierServiceImpl.java
  backend/src/main/java/com/ihl95/nuclear/supplier/domain/Supplier.java
  backend/src/test/java/com/ihl95/nuclear/supplier/controller/SupplierIntegrationTest.java
  backend/src/test/resources/test-data.sql
Labels: enhancement

#21 test(Supplier): unit tests
  backend/src/main/java/com/ihl95/nuclear/supplier/application/dto/SupplierDTO.java
  backend/src/test/java/com/ihl95/nuclear/nuclearPlant/service/NuclearPlantUnitTest.java
  backend/src/test/java/com/ihl95/nuclear/supplier/service/SupplierServiceTestMocks.java
  backend/src/test/java/com/ihl95/nuclear/supplier/service/SupplierUnitTest.java
Labels: enhancement

#22 Sonar-issues
  backend/src/main/java/com/ihl95/nuclear/NuclearPowerplantBackendApplication.java
  backend/src/main/java/com/ihl95/nuclear/equipment/application/dto/EquipmentDTO.java
  backend/src/main/java/com/ihl95/nuclear/equipment/application/mapper/EquipmentMapper.java
  backend/src/main/java/com/ihl95/nuclear/equipment/domain/Equipment.java
Labels: Sonar

#23 fix(Sonar): issues fixed
  .github/workflows/ci.yml
  backend/src/main/java/com/ihl95/nuclear/maintenancePlan/application/dto/MaintenancePlanDTO.java
  backend/src/main/java/com/ihl95/nuclear/maintenancePlan/application/mapper/MaintenancePlanMapper.java
  backend/src/main/java/com/ihl95/nuclear/maintenancePlan/domain/MaintenancePlan.java
  backend/src/main/java/com/ihl95/nuclear/nuclearPlant/application/mapper/NuclearPlantCompleteMapper.java
  backend/src/main/java/com/ihl95/nuclear/nuclearPlant/application/service/NuclearPlantService.java
  backend/src/main/java/com/ihl95/nuclear/nuclearPlant/application/service/NuclearPlantServiceImpl.java
  backend/src/main/java/com/ihl95/nuclear/nuclearPlant/domain/NuclearPlant.java
  backend/src/main/java/com/ihl95/nuclear/operator/application/dto/OperatorDTO.java
  backend/src/main/java/com/ihl95/nuclear/operator/domain/Operator.java
  backend/src/main/java/com/ihl95/nuclear/reactor/application/dto/ReactorDTO.java
  backend/src/main/java/com/ihl95/nuclear/reactor/domain/Reactor.java
  backend/src/main/java/com/ihl95/nuclear/sensor/application/dto/SensorDTO.java
  backend/src/main/java/com/ihl95/nuclear/sensor/application/mapper/SensorMapper.java
  backend/src/main/java/com/ihl95/nuclear/sensor/domain/Sensor.java
Labels: Bug, Sonar, Refactor

#26 fix(Sonar): Supplier tests class issues
  backend/src/main/java/com/ihl95/nuclear/supplier/application/controller/SupplierController.java
  backend/src/test/java/com/ihl95/nuclear/supplier/controller/SupplierIntegrationTest.java
Labels: Sonar, Test

#27 fix(Sonar): High issues fixed
  backend/src/main/java/com/ihl95/nuclear/equipment/application/mapper/EquipmentMapper.java
  backend/src/main/java/com/ihl95/nuclear/security/JwtUtil.java
  backend/src/main/java/com/ihl95/nuclear/sensor/application/mapper/SensorMapper.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/ihl95/nuclear/NuclearApplicationTests.java
Labels: Sonar

#28 fix(Sonar): High issue fixed and metadata for application.properties
  backend/src/main/java/com/ihl95/nuclear/maintenancePlan/application/mapper/MaintenancePlanMapper.java
  backend/src/main/resources/META-INF/additional-spring-configuration-metadata.json
Labels: Sonar

#29 fix(Sonar): packages and getJwtToken in testing refactored
  backend/src/main/java/com/ihl95/nuclear/controlSystem/application/dto/ControlSystemDTO.java
  backend/src/main/java/com/ihl95/nuclear/controlSystem/application/mapper/ControlSystemMapper.java
  backend/src/main/java/com/ihl95/nuclear/controlSystem/domain/ControlSystem.java
  backend/src/main/java/com/ihl95/nuclear/controlSystem/domain/enums/ControlSystemType.java
  backend/src/main/java/com/ihl95/nuclear/emergencyPlan/application/dto/EmergencyPlanDTO.java
  backend/src/main/java/com/ihl95/nuclear/emergencyPlan/application/mapper/EmergencyPlanMapper.java
  backend/src/main/java/com/ihl95/nuclear/emergencyPlan/application/service/EmergencyPlanService.java
  backend/src/main/java/com/ihl95/nuclear/emergencyPlan/application/service/EmergencyPlanServiceImpl.java
  backend/src/main/java/com/ihl95/nuclear/emergencyPlan/domain/EmergencyPlan.java
  backend/src/main/java/com/ihl95/nuclear/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/ihl95/nuclear/incident/domain/Incident.java
  backend/src/main/java/com/ihl95/nuclear/maintenance/application/mapper/MaintenanceMapper.java
  backend/src/main/java/com/ihl95/nuclear/maintenance/domain/Maintenance.java
  backend/src/main/java/com/ihl95/nuclear/maintenancePlan/application/dto/MaintenancePlanDTO.java
  backend/src/main/java/com/ihl95/nuclear/maintenancePlan/application/mapper/MaintenancePlanMapper.java
  backend/src/main/java/com/ihl95/nuclear/maintenancePlan/application/service/MaintenancePlanService.java
  backend/src/main/java/com/ihl95/nuclear/maintenancePlan/application/service/MaintenancePlanServiceImpl.java
  backend/src/main/java/com/ihl95/nuclear/maintenancePlan/domain/MaintenancePlan.java
  backend/src/main/java/com/ihl95/nuclear/nuclearPlant/application/controller/NuclearPlantController.java
  backend/src/main/java/com/ihl95/nuclear/nuclearPlant/application/dto/NuclearPlantCompleteDTO.java
  backend/src/main/java/com/ihl95/nuclear/nuclearPlant/application/dto/NuclearPlantDTO.java
  backend/src/main/java/com/ihl95/nuclear/nuclearPlant/application/exception/NuclearPlantException.java
  backend/src/main/java/com/ihl95/nuclear/nuclearPlant/application/mapper/NuclearPlantCompleteMapper.java
  backend/src/main/java/com/ihl95/nuclear/nuclearPlant/application/service/NuclearPlantService.java
  backend/src/main/java/com/ihl95/nuclear/nuclearPlant/application/service/NuclearPlantServiceImpl.java
  backend/src/main/java/com/ihl95/nuclear/nuclearPlant/domain/NuclearPlant.java
  backend/src/main/java/com/ihl95/nuclear/nuclearPlant/infraestructure/NuclearPlantRepository.java
  backend/src/main/java/com/ihl95/nuclear/operator/domain/Operator.java
  backend/src/main/java/com/ihl95/nuclear/reactor/domain/Reactor.java
  backend/src/main/java/com/ihl95/nuclear/sensorReading/application/dto/SensorReadingDTO.java
  backend/src/main/java/com/ihl95/nuclear/sensorReading/application/mapper/SensorReadingMapper.java
  backend/src/main/java/com/ihl95/nuclear/sensorReading/domain/SensorReading.java
  backend/src/test/java/com/ihl95/nuclear/nuclearPlant/controller/NuclearPlantIntegrationTest.java
  backend/src/test/java/com/ihl95/nuclear/nuclearPlant/service/NuclearPlantServiceTestMocks.java
  backend/src/test/java/com/ihl95/nuclear/nuclearPlant/service/NuclearPlantUnitTest.java
  backend/src/test/java/com/ihl95/nuclear/supplier/controller/SupplierIntegrationTest.java
Labels: Sonar, Refactor

#31 ci: Second update ci.yml
  .github/workflows/ci.yml
Labels: Github Actions

#32 docs: Update README.md
  README.md
Labels: Docs

#33 docs: Update README.md
  README.md
Labels: Docs

#34 fix(Sonar): some minor issues
  backend/src/main/java/com/ihl95/nuclear/anomaly/application/mapper/AnomalyMapper.java
  backend/src/main/java/com/ihl95/nuclear/incident/application/mapper/IncidentMapper.java
  backend/src/main/java/com/ihl95/nuclear/operator/application/dto/OperatorDTO.java
  backend/src/main/java/com/ihl95/nuclear/operator/application/mapper/OperatorMapper.java
Labels: Sonar

#35 fix(Sonar): medium issue
  backend/src/main/java/com/ihl95/nuclear/anomaly/application/mapper/AnomalyMapper.java
Labels: Sonar

#36 fix(Sonar): issues from last SonarCloud report
  backend/src/main/java/com/ihl95/nuclear/nuclearPlant/application/controller/NuclearPlantController.java
  backend/src/main/java/com/ihl95/nuclear/nuclearPlant/application/service/NuclearPlantServiceImpl.java
  backend/src/main/java/com/ihl95/nuclear/security/JwtRequestFilter.java
  backend/src/main/java/com/ihl95/nuclear/security/JwtUtil.java
  backend/src/main/java/com/ihl95/nuclear/security/controller/AuthController.java
  backend/src/main/java/com/ihl95/nuclear/supplier/application/controller/SupplierController.java
  backend/src/main/java/com/ihl95/nuclear/supplier/application/service/SupplierServiceImpl.java
  backend/src/main/java/com/ihl95/nuclear/user/CustomUserDetailsService.java
  backend/src/test/java/com/ihl95/nuclear/nuclearPlant/service/NuclearPlantUnitTest.java
  backend/src/test/java/com/ihl95/nuclear/security/AuthenticationProviderTest.java
  backend/src/test/java/com/ihl95/nuclear/security/CustomUserDetailsServiceTest.java
  backend/src/test/java/com/ihl95/nuclear/security/SecurityConfigurerTest.java
Labels: Sonar

#37 test(Security): Unit tests for different security methods
  backend/src/main/java/com/ihl95/nuclear/security/JwtUtil.java
  backend/src/test/java/com/ihl95/nuclear/security/JwtRequestFilterTest.java
  backend/src/test/java/com/ihl95/nuclear/security/JwtUtilTest.java
Labels: Sonar, Test

#38 security: Custom exception when username or password is not correct
  backend/src/main/java/com/ihl95/nuclear/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/ihl95/nuclear/security/controller/AuthController.java
  backend/src/main/java/com/ihl95/nuclear/security/exception/SecurityException.java
  backend/src/test/java/com/ihl95/nuclear/security/SecurityConfigurerTest.java
Labels: Sonar, Refactor

#42 test(Nuclear Plant): Tests and tests data refactored
  backend/src/test/java/com/ihl95/nuclear/nuclearPlant/controller/NuclearPlantIntegrationTest.java
  backend/src/test/java/com/ihl95/nuclear/nuclearPlant/service/NuclearPlantServiceTestMocks.java
  backend/src/test/resources/test-data.sql
Labels: Refactor, Test

#48 docs(Postman): Endpoint collection and environment
  postman/Nuke Endpoints.postman_collection.json
  postman/Nuke Local Env.postman_environment.json
Labels: Postman
